include/data/animal.h File Reference
Data Structures
struct Animal
struct AnimalLinkedList
struct AnimalLinkedListItem
Typedefs
typedef struct Animal Animal
typedef struct AnimalLinkedList AnimalLinkedList
typedef struct AnimalLinkedListItem AnimalLinkedListItem
Functions
Animal * animal_new (int id, char *name, char *species, int age, char *comment)
void animal_linked_list_sort (AnimalLinkedList *list, int(*cmp)(Animal *a, Animal *b))
AnimalLinkedList * animal_linked_list_new ()
void animal_linked_list_add_item (AnimalLinkedList *list, Animal *value)
Animal animal_linked_list_get_item (int index)
Typedef Documentation
Animal
typedef struct Animal Animal
AnimalLinkedList
typedef struct AnimalLinkedList AnimalLinkedList
AnimalLinkedListItem
typedef struct AnimalLinkedListItem AnimalLinkedListItem
Function Documentation
animal_linked_list_add_item()
void animal_linked_list_add_item (AnimalLinkedList * list, Animal * value)
Definition at line 93 of file animal.c.
References animal_linked_list_item_new(), AnimalLinkedList::firstItem, AnimalLinkedList::lastItem, AnimalLinkedListItem::next, AnimalLinkedListItem::prev, and AnimalLinkedList::size.
Referenced by main_window_new().
                                                                  {
    AnimalLinkedListItem* cur = list->firstItem;
    AnimalLinkedListItem* toAdd =
      animal_linked_list_item_new(value);
    if(list->size == 0){
        list->firstItem = toAdd;
        list->lastItem = toAdd;
        list->size ++;
        return;
    }
    int i;
    for(i=0; i<list->size-1; ++i){
        cur = cur->next;
    }
    cur->next = toAdd;
    list->lastItem = toAdd;
    toAdd->prev = cur;
    list->size ++;
};
animal_linked_list_get_item()
Animal animal_linked_list_get_item (int index)
animal_linked_list_new()
AnimalLinkedList* animal_linked_list_new ()
Definition at line 48 of file animal.c.
References AnimalLinkedList::size.
Referenced by main_window_new().
                        {
    AnimalLinkedList* list = malloc(sizeof(AnimalLinkedList));
    list->size = 0;
    return list;
}
animal_linked_list_sort()
void animal_linked_list_sort (AnimalLinkedList * list, int(*)(Animal *a, Animal *b) cmp)
Definition at line 55 of file animal.c.
References cmp(), AnimalLinkedList::firstItem, AnimalLinkedList::lastItem, AnimalLinkedListItem::next, AnimalLinkedListItem::prev, AnimalLinkedList::size, and AnimalLinkedListItem::value.
Referenced by callback_sort_click().
{
    int changed = 1;
    while(changed){
        changed = 0;
        AnimalLinkedListItem* cur = list->firstItem;
        for(int i=0; i<list->size-1; ++i){
            if((*cmp)(cur->value, cur->next->value)){
                changed = 1;
                int has_prev = list->firstItem != cur;
                int has_next = list->lastItem != cur->next;
                AnimalLinkedListItem* node_0 = has_prev ? cur->
      prev : NULL;
                AnimalLinkedListItem* node_1 = cur;
                AnimalLinkedListItem* node_2 = cur->next;
                AnimalLinkedListItem* node_3 = has_next ? cur->
      next->next : NULL;
                node_1->next = node_2->next;
                node_1->prev = node_2;
                node_2->next = node_1;
                node_2->prev = node_0;
                if(has_prev){
                    node_0->next = node_2;
                } else {
                    list->firstItem = node_2;
                }
                if(has_next){
                    node_3->prev = node_1;
                } else {
                    list->lastItem = node_1;
                }
                cur = node_2;
            }
            cur = cur->next;
        }
    }
}
animal_new()
Animal* animal_new (int id, char * name, char * species, int age, char * comment)
Definition at line 33 of file animal.c.
References Animal::age, Animal::comment, Animal::id, Animal::name, and Animal::species.
Referenced by main_window_new().
                                                                     {
    Animal* animal = malloc(sizeof(Animal));
    animal->id = id;
    animal->name = malloc(strlen(name)+1);
    strcpy(animal->name, name);
    animal->species = malloc(strlen(species)+1);
    strcpy(animal->species, species);
    animal->age = age;
    animal->comment = malloc(strlen(comment)+1);
    strcpy(animal->comment, comment);
    return animal;
}